import sys
path = r'O:\nestjs-boilerplate-main\nestjs-boilerplate-main\src\trips\trips.service.ts'
with open(path, 'r', encoding='utf-8') as f:
    content = f.read()

old = (
    "      // Create trip - maChuyenDi is auto-generated by database via @PrimaryGeneratedColumn('uuid')\n"
    "      const chuyenDi = manager.create(ChuyenDi, {\n"
    "        ...data,\n"
    "        // Don't set maChuyenDi - let DB auto-generate UUID\n"
    "        khachHang: customer,\n"
    "        xe,\n"
    "        bangGia,\n"
    "        giaUocTinh: giaUocTinh.giaUocTinh,\n"
    "        trangThai: 'REQUESTED', // default status (waiting for driver matching)\n"
    "        maTaiXe: data.maTaiXe ?? undefined, // optional driver assignment\n"
    "      });"
)

new = (
    "      // Create trip - maChuyenDi is auto-generated by database via @PrimaryGeneratedColumn('uuid')\n"
    "      const chuyenDi = manager.create(ChuyenDi, {\n"
    "        // Only map actual entity column fields explicitly (no spread of raw FK strings)\n"
    "        diemDon: data.diemDon,\n"
    "        diemDen: data.diemDen,\n"
    "        quangDuongKm: data.quangDuongKm,\n"
    "        viDoDon: data.viDoDon,\n"
    "        kinhDoDon: data.kinhDoDon,\n"
    "        viDoDen: data.viDoDen,\n"
    "        kinhDoDen: data.kinhDoDen,\n"
    "        // Relations - set via entity objects (not raw FK strings)\n"
    "        khachHang: customer,\n"
    "        xe,\n"
    "        bangGia,\n"
    "        // Calculated / default fields\n"
    "        giaUocTinh: giaUocTinh.giaUocTinh,\n"
    "        trangThai: 'REQUESTED', // default status (waiting for driver matching)\n"
    "      });"
)

if old in content:
    content = content.replace(old, new)
    with open(path, 'w', encoding='utf-8') as f:
        f.write(content)
    print('SUCCESS')
else:
    print('NOT FOUND')
    idx = content.find('manager.create(ChuyenDi')
    if idx >= 0:
        print(repr(content[idx:idx+600]))
