import {
  Injectable,
  NotFoundException,
  BadRequestException,
  ForbiddenException,
} from '@nestjs/common';
import { InjectRepository } from '@nestjs/typeorm';
import { Repository } from 'typeorm';
import { v4 as uuidv4 } from 'uuid';
import { BaseService } from '../common/base/base.service';
import { Xe } from '../entities/xe.entity';
import { KhachHang } from '../entities/khach-hang.entity';
import { LoaiXe } from '../entities/loai-xe.entity';
import { CreateVehicleDto } from './dto/create-vehicle.dto';
import { UpdateVehicleDto } from './dto/update-vehicle.dto';

/**
 * Vehicles Service - Vehicle Management
 * Extends BaseService for standard CRUD operations
 * Adds custom logic for customer-specific vehicle access
 */
@Injectable()
export class VehiclesService extends BaseService<Xe> {
  constructor(
    @InjectRepository(Xe)
    private readonly xeRepo: Repository<Xe>,
    @InjectRepository(KhachHang)
    private readonly khachHangRepo: Repository<KhachHang>,
    @InjectRepository(LoaiXe)
    private readonly loaiXeRepo: Repository<LoaiXe>,
  ) {
    super(xeRepo);
  }

  /**
   * Create a new vehicle for the logged-in customer
   * Finds customer by userId (maNguoiDung from JWT token)
   * Auto-generates maXe and ma for the vehicle
   * @param userId - User ID from JWT token (maNguoiDung)
   * @param dto - Create vehicle DTO
   * @returns Created vehicle
   */
  async createForCustomer(userId: string, dto: CreateVehicleDto): Promise<Xe> {
    // Find customer via nguoiDung.maNguoiDung relationship
    const customer = await this.khachHangRepo.findOne({
      where: {
        nguoiDung: { maNguoiDung: userId } as any,
      },
      relations: ['nguoiDung'],
    });
    if (!customer) {
      throw new NotFoundException(
        'Khách hàng không tồn tại. Vui lòng liên hệ quản trị viên.',
      );
    }

    // Verify vehicle type exists
    const loaiXe = await this.loaiXeRepo.findOne({
      where: { maLoaiXe: dto.maLoaiXe } as any,
    });
    if (!loaiXe) {
      throw new BadRequestException('Loại xe không tồn tại');
    }

    // Auto-generate ma field (secondary identifier)
    const ma = `XE-${Date.now()}-${uuidv4().substring(0, 8)}`;

    // Create vehicle (maXe will be auto-generated by DB as UUID)
    const vehicle = this.xeRepo.create({
      ma,
      bienSo: dto.bienSo,
      hangXe: dto.hangXe,
      dongXe: dto.dongXe,
      mauXe: dto.mauXe,
      cauTrucSangSo: dto.cauTrucSangSo,
      khachHang: customer,
      loaiXe,
    });

    return this.xeRepo.save(vehicle);
  }

  /**
   * Get all vehicles of the logged-in customer
   * @param userId - User ID from JWT token (maNguoiDung)
   * @returns List of vehicles owned by the customer
   */
  async findAllByCustomer(userId: string): Promise<Xe[]> {
    return this.xeRepo.find({
      where: {
        khachHang: {
          nguoiDung: { maNguoiDung: userId } as any,
        } as any,
      },
      relations: ['loaiXe', 'khachHang', 'khachHang.nguoiDung'],
      withDeleted: false,
    });
  }

  /**
   * Get a specific vehicle by ID
   * Ensures the vehicle belongs to the logged-in customer
   * @param maXe - Vehicle ID (UUID)
   * @param userId - User ID from JWT token (maNguoiDung)
   * @returns Vehicle details
   */
  async findOneByCustomer(maXe: string, userId: string): Promise<Xe> {
    const vehicle = await this.xeRepo.findOne({
      where: { maXe } as any,
      relations: ['loaiXe', 'khachHang', 'khachHang.nguoiDung'],
      withDeleted: false,
    });

    if (!vehicle) {
      throw new NotFoundException('Xe không tồn tại');
    }

    // Check ownership - verify vehicle belongs to current user
    if (vehicle.khachHang?.nguoiDung?.maNguoiDung !== userId) {
      throw new ForbiddenException('Xe này không thuộc về bạn');
    }

    return vehicle;
  }

  /**
   * Update a vehicle
   * Only allow updates to vehicles owned by the customer
   * @param maXe - Vehicle ID (UUID)
   * @param userId - User ID from JWT token (maNguoiDung)
   * @param dto - Update vehicle DTO
   * @returns Updated vehicle
   */
  async updateByCustomer(
    maXe: string,
    userId: string,
    dto: UpdateVehicleDto,
  ): Promise<Xe> {
    const vehicle = await this.findOneByCustomer(maXe, userId);

    // If updating loai xe, verify it exists
    if (dto.maLoaiXe) {
      const loaiXe = await this.loaiXeRepo.findOne({
        where: { maLoaiXe: dto.maLoaiXe } as any,
      });
      if (!loaiXe) {
        throw new BadRequestException('Loại xe không tồn tại');
      }
      vehicle.loaiXe = loaiXe;
    }

    // Update other fields
    if (dto.bienSo) vehicle.bienSo = dto.bienSo;
    if (dto.hangXe) vehicle.hangXe = dto.hangXe;
    if (dto.dongXe) vehicle.dongXe = dto.dongXe;
    if (dto.mauXe !== undefined) vehicle.mauXe = dto.mauXe;
    if (dto.cauTrucSangSo !== undefined)
      vehicle.cauTrucSangSo = dto.cauTrucSangSo;

    return this.xeRepo.save(vehicle);
  }

  /**
   * Delete a vehicle
   * Only allow deletion of vehicles owned by the customer
   * @param maXe - Vehicle ID (UUID)
   * @param userId - User ID from JWT token (maNguoiDung)
   * @returns Deleted vehicle
   */
  async removeByCustomer(maXe: string, userId: string): Promise<Xe> {
    const vehicle = await this.findOneByCustomer(maXe, userId);
    return this.xeRepo.remove(vehicle);
  }
}
