import { IsInt, IsNotEmpty, IsString, Min } from 'class-validator';
import { Type } from 'class-transformer';
import { ApiProperty } from '@nestjs/swagger';

/**
 * Create Loại Xe (Vehicle Type) DTO
 *
 * Used for creating new vehicle types in the system.
 * The maLoaiXe (ID) is auto-generated by the system as UUID.
 */
export class CreateLoaiXeDto {
  @ApiProperty({
    example: 4,
    description: 'Số chỗ ngồi (Number of seats)',
    minimum: 1,
  })
  @Type(() => Number)
  @IsInt()
  @Min(1, { message: 'Số chỗ phải lớn hơn 0' })
  soCho!: number;

  @ApiProperty({
    example: 'Tự động',
    description: 'Hộp số (Transmission type)',
  })
  @IsString()
  @IsNotEmpty()
  hopSo!: string;

  @ApiProperty({
    example: 'Honda Civic',
    description:
      'Phân khúc / Tên xe (Vehicle segment or vehicle name) - e.g. "Honda Civic", "Toyota Vios 4 chỗ", "Hyundai i10 tự động"',
  })
  @IsString()
  @IsNotEmpty()
  phanKhuc!: string;
}
